language: node_js
node_js:
  - '8'
  - '10'
script:
  - xo
  - node lib/build
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  - provider: script
    script: node lib/publish
    skip_cleanup: true
    on:
      branch:
        - master
        - greenkeeper/**
